apiVersion: v1
kind: Deployment
metadata:
  name: dls-be-deployment-dev
spec:
  template:
    spec:
      containers:
        - name: dls-be-dev
          image: fleeforezz/data-labeling-be:1.1-beta # <-Jenkins update this 