###################
# Deployment Object
###################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dls-be-deployment
spec:
  selector:
    matchLabels:
      app: dls-be
  replicas: 2
  template:
    metadata:
      labels:
        app: dls-be
    spec:
      automountServiceAccountToken: false
      containers:
        - name: dls-be
          image: fleeforezz/dls-be:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dls-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /data/dls-backend
              name: dls-storage
            - mountPath: /config
              name: dls-config
      volumes:
        - name: dls-storage
          persistentVolumeClaim:
            claimName: dls-pvc
        - name: dls-config
          configMap:
            name: dls-config
