################
# Service Object
################

apiVersion: v1
kind: Service
metadata:
  name: dls-be-service-dev
spec:
  type: NodePort
  selector:
    app: dls-be-dev
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32545